/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'workspace-config-save': EventHandler<never, never>
    'get-workspace-config': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'track-error-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'save-workspace-config': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'workspace.config.save'; data: never }>
    'run-digest': EventHandler<never, { topic: 'digest.per-user'; data: never }>
    'manual-digest-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'format-dev-digests': EventHandler<never, never>
    'digest-preview-api': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'daily-digest-trigger': CronHandler<never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
  }
    
}